### ISSUE TITLE
Issue: Pre-K Color Selection Game

### ISSUE THREAD

**Issue by TheMartinUriarte** [dkingdon/Growth-Academy#8]
[https://github.com/dkingdon/Growth-Academy/blob/d81e866a9d7a523e673ae3f56cf04948145e920e/public/scripts/controllers/pkColorsController.js#L61](url)

When selecting the incorrect color, it shows "The color you chose was {correct color here}". This should read either "The color you chose was {selected color here}" or "The correct color was {correct color here}".

**Comment by dkingdon** [comment]
Thanks, committed the color fix.
